### ISSUE TITLE
Configurar integração com MongoDB

### ISSUE THREAD

**Issue by yrachid** [aceleradora-TW/sistema-de-votacao#10]
### Contexto

O projeto está hospedado no Heroku, que por sua vez disponibiliza instâncias de MongoDB através de uma integração com o [MLab](https://mlab.com/). 

Tendo isto em mente, esta card tem por objetivo configurar o projeto para integrar-se ao MongoDB em diferentes ambientes:

- Desenvolvimento
- Staging

Para integração com MLab, [o Heroku irá expor uma variável de ambiente para nossa aplicação conectar-se ao Mongo](https://devcenter.heroku.com/articles/mongolab#getting-your-connection-uri).

Existe a biblioteca [mongoose](http://mongoosejs.com/), que faz a conexão com o Mongo e também nos ajuda a mapear e manipular (criar, editar, deletar, atualizar, etc.) os documentos do MongoDB desde a nossa aplicação.

### Tarefas

Para termos uma integração consistente entre a aplicação e o Mongo DB nos diferentes ambientes, precisamos:

__Configurar o projeto para conectar-se ao Mongo com o uso da Mongoose__

Se olharmos as dependências atuais do projeto, será possível ver que o mongoose já está entre as nossas dependências de produção, porém, a aplicação ainda não utiliza o módulo para nada. Devemos configurar a aplicação para usar o mongoose e conectar-se ao Mongo usando a variável de ambiente criada pelo Heroku. 

No caso dos ambientes locais, idealmente devemos decidir se:

* Vamos criar uma variável de ambiente com o mesmo nome da variável do Heroku
* Vamos deixar um valor hardcoded caso a variável não exista

Podemos estudar a possibilidade de usar o [dotenv](https://github.com/motdotla/dotenv) para nos ajudar a lidar com essas variáveis de ambiente.

__Configurar uma estratégia para executar o mongo local__

Hoje em dia, os nossos scripts Npm possuem tarefas(tasks) para automatizar a execução de um container Docker do mongoDB. Sendo estas as seguintes:

```
docker:db:start
``` 

Iniciará  um container docker do mongo em background, expondo a porta `27017` (porta default do MongoDB).

```
docker:db:stop
```

Pára o container docker executando atualmente.

```
docker:db:console
```

Conecta-se ao container que está executando e abre o console do Mongo, para que se possa executar consultas diretamente ao banco de dados.

__Devemos decidir se:__:

Faz sentido manter essa configuração do Docker ou instruimos as pessoas a instalarem o Mongo em suas máquinas?

__Ter um teste de integração:__

Idealmente, para garantir que a integração com o Mongo funciona, poderíamos ter um teste de integração, não muito complexo, que garanta que a aplicação consegue se comunicar com o mongo de maneira efetiva.

**Comment by yrachid** [comment]
Podem haver problemas no CircleCI. 

https://circleci.com/docs/2.0/postgres-config/#using-dockerize

**Comment by luanadiasf** [comment]
When I access my URL this error appears
"Nightscout - Boot error
Unable to connect to Mongo"

How do I do??
